import json

mapping = {
    27: "Morning & Evening",
    28: "Before Sleeping",
    1: "Upon Waking Up",
    6: "Entering Restroom",
    7: "Leaving Restroom",
    8: "Before Ablution",
    9: "After Ablution",
    10: "Leaving Home",
    11: "Entering Home",
    12: "Going to Mosque",
    13: "Entering Mosque",
    14: "Leaving Mosque",
    15: "Hearing Athan",
    2: "Getting Dressed",
    3: "New Clothes",
    4: "New Clothes (Others)",
    5: "Undressing",
    16: "Starting Prayer",
    17: "During Ruku'",
    18: "Rising from Ruku'",
    19: "During Sujood",
    20: "Between Prostrations",
    21: "Recitation Prostration",
    22: "At-Tashahhud",
    23: "Blessings on Prophet",
    24: "Before Ending Prayer",
    25: "After Prayer",
    26: "Istikharah",
    29: "Stirring in Night",
    30: "Fear/Loneliness at Night",
    31: "Bad Dream/Nightmare",
    32: "Qunut in Witr",
    33: "After Witr Prayer",
    34: "Worry & Grief",
    35: "Anguish",
    36: "Meeting Adversary/Ruler",
    37: "Oppression of Rulers",
    38: "Against Enemy",
    39: "Fear of Harm",
    40: "Doubt in Faith",
    41: "Settling Debt",
    42: "Satan's Distraction",
    43: "Becoming Difficult",
    44: "If Sin is Committed",
    45: "Satan's Promptings",
    46: "Dislike/Failure",
    47: "New Parents Congratulation",
    48: "Protection for Children",
    49: "Visiting the Sick",
    50: "Reward for Visiting Sick",
    51: "Terminally Ill",
    52: "Encouraging Dying Person",
    53: "When Tragedy Strikes",
    54: "Closing Eyes of Dead",
    55: "Funeral Prayer (Adult)",
    56: "Funeral Prayer (Child)",
    57: "Bereaved",
    58: "Placing in Grave",
    59: "After Burying",
    60: "Visiting Graves",
    61: "Wind Blows",
    62: "Thunder",
    63: "Dua for Rain",
    64: "When it Rains",
    65: "After it Rains",
    66: "Withholding Rain",
    67: "Sighting New Moon",
    68: "Breaking Fast",
    69: "Before Eating",
    70: "After Eating",
    71: "Dua for Host",
    72: "Offer of Drink",
    73: "Breaking Fast with Host",
    74: "Declining Food",
    75: "Rudeness to Fasting Person",
    76: "First Dates",
    77: "Sneezing",
    78: "Disbeliever Sneezing",
    79: "For the Groom",
    80: "Groom's Supplication",
    81: "Before Intercourse",
    82: "Anger",
    83: "Afflicted by Misfortune",
    84: "Sitting in Assembly",
    85: "Expiation of Assembly",
    86: "May Allah Forgive You",
    87: "Good Done to You",
    88: "Protection from Dajjal",
    89: "Love for Allah's Sake",
    90: "Share of Wealth",
    91: "Receipt of Loan",
    92: "Fear of Shirk",
    93: "May Allah Bless You",
    94: "Against Evil Portent",
    95: "Riding Vehicle",
    96: "Traveling",
    97: "Entering Town/City",
    98: "Entering Market",
    99: "Vehicle Fails",
    100: "Traveler to Resident",
    101: "Resident to Traveler",
    102: "Glorifying on Journey",
    103: "Traveler at Dawn",
    104: "Layover on Journey",
    105: "Returning from Journey",
    106: "Pleasure/Displeasure",
    107: "Blessings on Prophet",
    108: "Greeting of Salam",
    109: "Reply to Disbeliever",
    110: "Cock's Crow/Donkey's Bray",
    111: "Dog Barking",
    112: "Spoken Ill To",
    113: "Praising a Muslim",
    114: "When Praised",
    115: "Talbiyah (Hajj/Umrah)",
    116: "Passing Black Stone",
    117: "Corner to Black Stone",
    118: "Safa and Marwah",
    119: "Day of Arafat",
    120: "At Muzdalifah",
    121: "Stoning Pillars",
    122: "Surprised/Startled",
    123: "Pleasurable Event",
    124: "Pain in Body",
    125: "Fear of Evil Eye",
    126: "Frightened",
    127: "Slaughtering/Sacrificing",
    128: "Foil Devil's Plots",
    129: "Repentance & Forgiveness",
    130: "Excellence of Dhikr",
    131: "Prophet's Dhikr",
    132: "Goodness & Etiquette"
}

file_path = 'src/data/hisn_en.json'

with open(file_path, 'r', encoding='utf-8-sig') as f:
    data = json.load(f)

for item in data.get('English', []):
    id_val = item.get('ID')
    if id_val in mapping:
        item['TITLE'] = mapping[id_val]

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Shortened titles in hisn_en.json")
